### PR TITLE
[noetic-devel] python3 compatibility + green CI on ROS noetic

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Goes along https://github.com/clearpathrobotics/robot_upstart/pull/96

Uses the Python3 compatibility fixes from #96  and adds noetic CI configuration + fixes the roslint errors reported

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Now part of #96

**Comment by mikaelarguedas** [comment]
This PR build upon #96 and fixes the issues to get green ci.
@mikepurvis would this be sufficient for an initial noetic release ? or are there other points to address to have a noetic deb of this package (happy to help if needed)

**Review by 130s — APPROVED** [review]
Haven't looked into the entire repo to find if there are anything missing, but the changes in this PR looks great to me.

**Comment by civerachb-cpr** [comment]
This looks good to me.  I've tested it in a VM with Noetic and it appears to work as-desired.
@mikepurvis since you're the maintainer of this package I've requested your review.

**Comment by mikepurvis** [comment]
Looks great— sorry for the long silence here. @civerachb-cpr, @tonybaltovski please feel free to take over the formal maintainership of this repo, as we haven't used it for some time on the OTTO platforms.

**Review by mikepurvis — APPROVED** [review]

**Pull request merged**
